// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6c6Nhhw8Uf22_m0g5oZ3NdfY6-vXy7j4',
    appId: '1:980197324755:web:ee629bb1773c012d57e126',
    messagingSenderId: '980197324755',
    projectId: 'projectmanager-45060',
    authDomain: 'projectmanager-45060.firebaseapp.com',
    storageBucket: 'projectmanager-45060.firebasestorage.app',
    measurementId: 'G-G2VMHQWEGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQr-IReaz6wEDs_fszZMppulAs2f0dTOg',
    appId: '1:980197324755:android:fad3eace23788e2f57e126',
    messagingSenderId: '980197324755',
    projectId: 'projectmanager-45060',
    storageBucket: 'projectmanager-45060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsYAQRw_6IbXloqfTvBu-w_NnNC9UXfD0',
    appId: '1:980197324755:ios:3a14146865816c4b57e126',
    messagingSenderId: '980197324755',
    projectId: 'projectmanager-45060',
    storageBucket: 'projectmanager-45060.firebasestorage.app',
    iosBundleId: 'com.example.webProjectManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsYAQRw_6IbXloqfTvBu-w_NnNC9UXfD0',
    appId: '1:980197324755:ios:3a14146865816c4b57e126',
    messagingSenderId: '980197324755',
    projectId: 'projectmanager-45060',
    storageBucket: 'projectmanager-45060.firebasestorage.app',
    iosBundleId: 'com.example.webProjectManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6c6Nhhw8Uf22_m0g5oZ3NdfY6-vXy7j4',
    appId: '1:980197324755:web:f167f0fa96fec6fe57e126',
    messagingSenderId: '980197324755',
    projectId: 'projectmanager-45060',
    authDomain: 'projectmanager-45060.firebaseapp.com',
    storageBucket: 'projectmanager-45060.firebasestorage.app',
    measurementId: 'G-12CGQPTNZ3',
  );
}
